# Generated by Django 2.2.7 on 2020-06-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alluser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('mobile', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Celve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clcode', models.CharField(max_length=256, unique=True)),
                ('clname', models.TextField(max_length=256)),
                ('last_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='usercelve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clname', models.CharField(max_length=256)),
                ('nums', models.IntegerField(default=0)),
                ('last_time', models.DateTimeField(auto_now_add=True)),
                ('shanchu', models.FloatField(null=True)),
                ('celve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Celve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Alluser')),
            ],
        ),
    ]
