# Generated by Django 2.2.7 on 2020-06-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gupiaolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9, verbose_name='股票代码')),
                ('codename', models.CharField(max_length=20, verbose_name='股票名称')),
            ],
        ),
        migrations.CreateModel(
            name='Jiaoyiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('isover', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='kline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('preclose', models.FloatField(null=True)),
                ('turn', models.FloatField(null=True)),
                ('dif', models.FloatField(null=True)),
                ('dea', models.FloatField(null=True)),
                ('hist', models.FloatField(null=True)),
                ('kdjK', models.FloatField(null=True)),
                ('kdjD', models.FloatField(null=True)),
                ('kdjJ', models.FloatField(null=True)),
                ('day5', models.FloatField(null=True)),
                ('day10', models.FloatField(null=True)),
                ('day20', models.FloatField(null=True)),
                ('upper', models.FloatField(null=True)),
                ('middle', models.FloatField(null=True)),
                ('lower', models.FloatField(null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gupiaolist')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Jiaoyiday')),
            ],
        ),
        migrations.CreateModel(
            name='jisuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day5to10', models.NullBooleanField()),
                ('day5to20', models.NullBooleanField()),
                ('day10to20', models.NullBooleanField()),
                ('MACD', models.NullBooleanField()),
                ('buynumtwo', models.NullBooleanField()),
                ('buynum5', models.NullBooleanField()),
                ('buynum20', models.NullBooleanField()),
                ('KDJ', models.NullBooleanField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gupiaolist')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Jiaoyiday')),
            ],
        ),
    ]
