# Generated by Django 3.0.6 on 2020-08-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gupiaomsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tusharecode', models.CharField(max_length=9)),
                ('dongfangcaifu', models.CharField(max_length=9)),
                ('listdate', models.DateField(null=True)),
                ('industry', models.CharField(max_length=50, null=True)),
                ('holdernum', models.IntegerField(null=True)),
                ('holderenddate', models.DateField(null=True)),
                ('holderfloat', models.BigIntegerField(null=True)),
                ('holdercirc', models.BigIntegerField(null=True)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Gupiaolist')),
            ],
        ),
    ]
