# Generated by Django 2.2.7 on 2020-04-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiaoyiday',
            name='isover',
            field=models.NullBooleanField(),
        ),
    ]
