# Generated by Django 2.2.7 on 2020-06-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jisuan',
            name='buynum3chang',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='jisuan',
            name='buynum3up',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='jisuan',
            name='buynum5chang',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='jisuan',
            name='buynum5up',
            field=models.NullBooleanField(),
        ),
    ]
